%YAML:1.0

# Scene size [px] / mandatory
canvasSizePixel: [800, 600]
# Scene size [m] / mandatory
canvasSizeMeter: [8., 6.]

# Time step for simulation
# dt: 0.001

# Ball radius [m]
ballRadiusMtr: 0.12

# Ball speed range [m/s]
ballShotSpeedLimitsMPS: [10, 50]
